# Uncomment the php version that you want to test.
# Currently the library is based on PHP 7.4.
FROM php:7.4-cli

# If using PHP v8.x, use any of the following images.
# FROM php:8.0-cli
# FROM php:8.1-cli
# FROM php:8.2-cli

# Install dependencies
RUN apt update && \
    apt upgrade -y && \
    apt install -y \
    git \
    curl \
    zip \
    unzip

# Install xdebug via PECL as not provided by PHP Source
RUN pecl install xdebug-3.1.5 \
    && docker-php-ext-enable xdebug

# If using PHP 8.x, use the following to install xdebug. This is for future reference.
# RUN pecl install xdebug \
#     && docker-php-ext-enable xdebug

# Clear cache
RUN apt clean && \
    rm -rf /var/lib/apt/lists/*

# Install composer (get latest v2, change to `--1` if you want to install the latest v1).
RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/local/bin --filename=composer

COPY . /usr/src/lib
WORKDIR /usr/src/lib

CMD [ "php"]
